---
- hosts: prod


  tasks:
    - name: clone repository
      git:
        repo: https://github.com/AhMeD7493/Cafe-App.git
        dest: ~/devops-test/cafe-app-img
        clone: yes
        update: yes

    - name: create docker image
      command: docker build -t cafe-app:latest ~/devops-test/cafe-app-img
      args:
        chdir: ~/devops-test/


    
    - name: create tag to push image to docker hub
      command: docker tag cafe-app:latest ahmed7493/cafe-app:latest

    - name: push docker image
      command: docker push ahmed7493/cafe-app:latest
        
